/- GENERATED by tools/formalize_tax.py — do not edit by hand.
   Indian income tax, new regime FY 2024-25 (simplified pilot:
   no cess, surcharge, marginal relief, or deductions).
   Slabs: ≤300 000: 0% · ≤700 000: 5% · ≤1 000 000: 10% · ≤1 200 000: 15% · ≤1 500 000: 20% · ∞: 30% -/

namespace Compliance

/-- Income tax (₹) under the new-regime slab table, before §87A rebate. -/
def slabTax (i : Nat) : Nat :=
    if i ≤ 300000 then 0
    else
    if i ≤ 700000 then 0 + (i - 300000) * 5 / 100
    else
    if i ≤ 1000000 then 20000 + (i - 700000) * 10 / 100
    else
    if i ≤ 1200000 then 50000 + (i - 1000000) * 15 / 100
    else
    if i ≤ 1500000 then 80000 + (i - 1200000) * 20 / 100
    else
    140000 + (i - 1500000) * 30 / 100

/-- Tax payable after the §87A rebate (nil up to ₹700000). -/
def taxPayable (i : Nat) : Nat :=
  if i ≤ 700000 then 0 else slabTax i

-- Kernel-checked regression facts at every slab boundary (and just past it).
-- Stated as `example`s: they are facts, not claims — the auditor skips them.
example : slabTax 300000 = 0 := by decide
example : slabTax 300001 = 0 := by decide
example : slabTax 700000 = 20000 := by decide
example : slabTax 700001 = 20000 := by decide
example : slabTax 1000000 = 50000 := by decide
example : slabTax 1000001 = 50000 := by decide
example : slabTax 1200000 = 80000 := by decide
example : slabTax 1200001 = 80000 := by decide
example : slabTax 1500000 = 140000 := by decide
example : slabTax 1500001 = 140000 := by decide
example : slabTax 1600000 = 170000 := by decide
example : slabTax 2500000 = 440000 := by decide

/-- §87A: taxable income up to the rebate limit ⇒ zero tax payable. -/
theorem rebate_nils_tax (i : Nat) (h : i ≤ 700000) :
    taxPayable i = 0 := by
  simp [taxPayable, h]

/-- Above the rebate limit the slab function is what you pay. -/
theorem above_rebate_pays_slab (i : Nat) (h : 700000 < i) :
    taxPayable i = slabTax i := by
  simp [taxPayable, Nat.not_le.mpr h]

end Compliance
