/- GENERATED by tools/formalize_tax.py — do not edit by hand.
   Indian income tax, three regimes, compiled from the published slab tables.
   Simplified pilot: no surcharge, deductions, or capital-gains rates; the 4%
   health-and-education cess is provided as a helper. Informational only —
   not tax advice. -/

namespace Compliance

/-! ### New regime, FY 2024-25 (AY 2025-26)
    Slabs: ≤300000:0% · ≤700000:5% · ≤1000000:10% · ≤1200000:15% · ≤1500000:20% · ∞:30% · §87A rebate to ₹700000 · marginal relief -/

/-- Slab tax (₹) before rebate, New regime, FY 2024-25 (AY 2025-26). -/
def nr24_slabTax (i : Nat) : Nat :=
    if i ≤ 300000 then 0
    else
    if i ≤ 700000 then 0 + (i - 300000) * 5 / 100
    else
    if i ≤ 1000000 then 20000 + (i - 700000) * 10 / 100
    else
    if i ≤ 1200000 then 50000 + (i - 1000000) * 15 / 100
    else
    if i ≤ 1500000 then 80000 + (i - 1200000) * 20 / 100
    else
    140000 + (i - 1500000) * 30 / 100

/-- Tax payable after §87A with marginal relief. -/
def nr24_payable (i : Nat) : Nat :=
  if i ≤ 700000 then 0 else min (nr24_slabTax i) (i - 700000)

example : nr24_slabTax 300000 = 0 := by decide
example : nr24_slabTax 300001 = 0 := by decide
example : nr24_slabTax 700000 = 20000 := by decide
example : nr24_slabTax 700001 = 20000 := by decide
example : nr24_slabTax 1000000 = 50000 := by decide
example : nr24_slabTax 1000001 = 50000 := by decide
example : nr24_slabTax 1200000 = 80000 := by decide
example : nr24_slabTax 1200001 = 80000 := by decide
example : nr24_slabTax 1500000 = 140000 := by decide
example : nr24_slabTax 1500001 = 140000 := by decide
example : nr24_payable 700000 = 0 := by decide
example : nr24_payable 700001 = 1 := by decide
example : nr24_payable 705000 = 5000 := by decide

/-- §87A (New regime, FY 2024-25 (AY 2025-26)): taxable income up to ₹700000 ⇒ zero tax payable. -/
theorem nr24_rebate_nils_tax (i : Nat) (h : i ≤ 700000) :
    nr24_payable i = 0 := by
  simp [nr24_payable, h]

/-- Marginal relief: one extra rupee of income above ₹700000 costs at most one
    extra rupee of tax — payable never exceeds income − 700000. -/
theorem nr24_marginal_relief (i : Nat) (h : 700000 < i) :
    nr24_payable i ≤ i - 700000 := by
  unfold nr24_payable
  rw [if_neg (Nat.not_le.mpr h)]
  exact Nat.min_le_right _ _

/-- Above the rebate limit you never pay more than the slab schedule. -/
theorem nr24_payable_le_slab (i : Nat) (h : 700000 < i) :
    nr24_payable i ≤ nr24_slabTax i := by
  unfold nr24_payable
  rw [if_neg (Nat.not_le.mpr h)]
  exact Nat.min_le_left _ _

/-! ### New regime, FY 2025-26 (AY 2026-27)
    Slabs: ≤400000:0% · ≤800000:5% · ≤1200000:10% · ≤1600000:15% · ≤2000000:20% · ≤2400000:25% · ∞:30% · §87A rebate to ₹1200000 · marginal relief -/

/-- Slab tax (₹) before rebate, New regime, FY 2025-26 (AY 2026-27). -/
def nr25_slabTax (i : Nat) : Nat :=
    if i ≤ 400000 then 0
    else
    if i ≤ 800000 then 0 + (i - 400000) * 5 / 100
    else
    if i ≤ 1200000 then 20000 + (i - 800000) * 10 / 100
    else
    if i ≤ 1600000 then 60000 + (i - 1200000) * 15 / 100
    else
    if i ≤ 2000000 then 120000 + (i - 1600000) * 20 / 100
    else
    if i ≤ 2400000 then 200000 + (i - 2000000) * 25 / 100
    else
    300000 + (i - 2400000) * 30 / 100

/-- Tax payable after §87A with marginal relief. -/
def nr25_payable (i : Nat) : Nat :=
  if i ≤ 1200000 then 0 else min (nr25_slabTax i) (i - 1200000)

example : nr25_slabTax 400000 = 0 := by decide
example : nr25_slabTax 400001 = 0 := by decide
example : nr25_slabTax 800000 = 20000 := by decide
example : nr25_slabTax 800001 = 20000 := by decide
example : nr25_slabTax 1200000 = 60000 := by decide
example : nr25_slabTax 1200001 = 60000 := by decide
example : nr25_slabTax 1600000 = 120000 := by decide
example : nr25_slabTax 1600001 = 120000 := by decide
example : nr25_slabTax 2000000 = 200000 := by decide
example : nr25_slabTax 2000001 = 200000 := by decide
example : nr25_slabTax 2400000 = 300000 := by decide
example : nr25_slabTax 2400001 = 300000 := by decide
example : nr25_payable 1200000 = 0 := by decide
example : nr25_payable 1200001 = 1 := by decide
example : nr25_payable 1205000 = 5000 := by decide

/-- §87A (New regime, FY 2025-26 (AY 2026-27)): taxable income up to ₹1200000 ⇒ zero tax payable. -/
theorem nr25_rebate_nils_tax (i : Nat) (h : i ≤ 1200000) :
    nr25_payable i = 0 := by
  simp [nr25_payable, h]

/-- Marginal relief: one extra rupee of income above ₹1200000 costs at most one
    extra rupee of tax — payable never exceeds income − 1200000. -/
theorem nr25_marginal_relief (i : Nat) (h : 1200000 < i) :
    nr25_payable i ≤ i - 1200000 := by
  unfold nr25_payable
  rw [if_neg (Nat.not_le.mpr h)]
  exact Nat.min_le_right _ _

/-- Above the rebate limit you never pay more than the slab schedule. -/
theorem nr25_payable_le_slab (i : Nat) (h : 1200000 < i) :
    nr25_payable i ≤ nr25_slabTax i := by
  unfold nr25_payable
  rw [if_neg (Nat.not_le.mpr h)]
  exact Nat.min_le_left _ _

/-! ### Old regime (individuals below 60)
    Slabs: ≤250000:0% · ≤500000:5% · ≤1000000:20% · ∞:30% · §87A rebate to ₹500000 -/

/-- Slab tax (₹) before rebate, Old regime (individuals below 60). -/
def old_slabTax (i : Nat) : Nat :=
    if i ≤ 250000 then 0
    else
    if i ≤ 500000 then 0 + (i - 250000) * 5 / 100
    else
    if i ≤ 1000000 then 12500 + (i - 500000) * 20 / 100
    else
    112500 + (i - 1000000) * 30 / 100

/-- Tax payable after §87A. -/
def old_payable (i : Nat) : Nat :=
  if i ≤ 500000 then 0 else old_slabTax i

example : old_slabTax 250000 = 0 := by decide
example : old_slabTax 250001 = 0 := by decide
example : old_slabTax 500000 = 12500 := by decide
example : old_slabTax 500001 = 12500 := by decide
example : old_slabTax 1000000 = 112500 := by decide
example : old_slabTax 1000001 = 112500 := by decide
example : old_payable 500000 = 0 := by decide
example : old_payable 500001 = 12500 := by decide
example : old_payable 505000 = 13500 := by decide

/-- §87A (Old regime (individuals below 60)): taxable income up to ₹500000 ⇒ zero tax payable. -/
theorem old_rebate_nils_tax (i : Nat) (h : i ≤ 500000) :
    old_payable i = 0 := by
  simp [old_payable, h]

/-- Old regime: above the rebate limit, payable is exactly the slab schedule. -/
theorem old_payable_eq_slab (i : Nat) (h : 500000 < i) :
    old_payable i = old_slabTax i := by
  unfold old_payable
  rw [if_neg (Nat.not_le.mpr h)]

/-- Health & education cess (4%), applied to tax payable. -/
def withCess (tax : Nat) : Nat := tax + tax * 4 / 100

example : withCess 0 = 0 := by decide
example : withCess 60000 = 62400 := by decide

/-- Cess never decreases tax. -/
theorem withCess_ge (t : Nat) : t ≤ withCess t := by
  unfold withCess; omega

end Compliance
