/- GENERATED by tools/formalize_tds.py — do not edit by hand.
   TDS deductibility thresholds, FY 2024-25 (simplified pilot:
   thresholds only, FY 2024-25; rates and PAN rules are
   out of scope). Informational only — not tax advice. -/

namespace Compliance

/-- §192A threshold (EPF premature withdrawal), ₹. -/
def threshold_192A : Nat := 50000

/-- TDS under §192A applies once the payment exceeds the threshold. -/
abbrev deductible_192A (paid : Nat) : Prop := threshold_192A < paid

example : ¬ deductible_192A 50000 := by decide
example : deductible_192A 50001 := by decide

/-- §192A: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_192A_mono (x y : Nat)
    (hx : deductible_192A x) (hxy : x ≤ y) : deductible_192A y := by
  unfold deductible_192A threshold_192A at hx ⊢
  omega

/-- §193 threshold (interest on securities), ₹. -/
def threshold_193 : Nat := 10000

/-- TDS under §193 applies once the payment exceeds the threshold. -/
abbrev deductible_193 (paid : Nat) : Prop := threshold_193 < paid

example : ¬ deductible_193 10000 := by decide
example : deductible_193 10001 := by decide

/-- §193: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_193_mono (x y : Nat)
    (hx : deductible_193 x) (hxy : x ≤ y) : deductible_193 y := by
  unfold deductible_193 threshold_193 at hx ⊢
  omega

/-- §194 threshold (dividend), ₹. -/
def threshold_194 : Nat := 5000

/-- TDS under §194 applies once the payment exceeds the threshold. -/
abbrev deductible_194 (paid : Nat) : Prop := threshold_194 < paid

example : ¬ deductible_194 5000 := by decide
example : deductible_194 5001 := by decide

/-- §194: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194_mono (x y : Nat)
    (hx : deductible_194 x) (hxy : x ≤ y) : deductible_194 y := by
  unfold deductible_194 threshold_194 at hx ⊢
  omega

/-- §194A threshold (bank and post-office interest), ₹. -/
def threshold_194A : Nat := 40000

/-- TDS under §194A applies once the payment exceeds the threshold. -/
abbrev deductible_194A (paid : Nat) : Prop := threshold_194A < paid

example : ¬ deductible_194A 40000 := by decide
example : deductible_194A 40001 := by decide

/-- §194A: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194A_mono (x y : Nat)
    (hx : deductible_194A x) (hxy : x ≤ y) : deductible_194A y := by
  unfold deductible_194A threshold_194A at hx ⊢
  omega

/-- §194A_senior threshold (bank interest, senior citizen), ₹. -/
def threshold_194A_senior : Nat := 50000

/-- TDS under §194A_senior applies once the payment exceeds the threshold. -/
abbrev deductible_194A_senior (paid : Nat) : Prop := threshold_194A_senior < paid

example : ¬ deductible_194A_senior 50000 := by decide
example : deductible_194A_senior 50001 := by decide

/-- §194A_senior: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194A_senior_mono (x y : Nat)
    (hx : deductible_194A_senior x) (hxy : x ≤ y) : deductible_194A_senior y := by
  unfold deductible_194A_senior threshold_194A_senior at hx ⊢
  omega

/-- §194B threshold (lottery and game winnings), ₹. -/
def threshold_194B : Nat := 10000

/-- TDS under §194B applies once the payment exceeds the threshold. -/
abbrev deductible_194B (paid : Nat) : Prop := threshold_194B < paid

example : ¬ deductible_194B 10000 := by decide
example : deductible_194B 10001 := by decide

/-- §194B: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194B_mono (x y : Nat)
    (hx : deductible_194B x) (hxy : x ≤ y) : deductible_194B y := by
  unfold deductible_194B threshold_194B at hx ⊢
  omega

/-- §194BB threshold (horse-race winnings), ₹. -/
def threshold_194BB : Nat := 10000

/-- TDS under §194BB applies once the payment exceeds the threshold. -/
abbrev deductible_194BB (paid : Nat) : Prop := threshold_194BB < paid

example : ¬ deductible_194BB 10000 := by decide
example : deductible_194BB 10001 := by decide

/-- §194BB: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194BB_mono (x y : Nat)
    (hx : deductible_194BB x) (hxy : x ≤ y) : deductible_194BB y := by
  unfold deductible_194BB threshold_194BB at hx ⊢
  omega

/-- §194C threshold (contractor payment (single)), ₹. -/
def threshold_194C : Nat := 30000

/-- TDS under §194C applies once the payment exceeds the threshold. -/
abbrev deductible_194C (paid : Nat) : Prop := threshold_194C < paid

example : ¬ deductible_194C 30000 := by decide
example : deductible_194C 30001 := by decide

/-- §194C: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194C_mono (x y : Nat)
    (hx : deductible_194C x) (hxy : x ≤ y) : deductible_194C y := by
  unfold deductible_194C threshold_194C at hx ⊢
  omega

/-- §194C_agg threshold (contractor payments (annual aggregate)), ₹. -/
def threshold_194C_agg : Nat := 100000

/-- TDS under §194C_agg applies once the payment exceeds the threshold. -/
abbrev deductible_194C_agg (paid : Nat) : Prop := threshold_194C_agg < paid

example : ¬ deductible_194C_agg 100000 := by decide
example : deductible_194C_agg 100001 := by decide

/-- §194C_agg: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194C_agg_mono (x y : Nat)
    (hx : deductible_194C_agg x) (hxy : x ≤ y) : deductible_194C_agg y := by
  unfold deductible_194C_agg threshold_194C_agg at hx ⊢
  omega

/-- §194D threshold (insurance commission), ₹. -/
def threshold_194D : Nat := 15000

/-- TDS under §194D applies once the payment exceeds the threshold. -/
abbrev deductible_194D (paid : Nat) : Prop := threshold_194D < paid

example : ¬ deductible_194D 15000 := by decide
example : deductible_194D 15001 := by decide

/-- §194D: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194D_mono (x y : Nat)
    (hx : deductible_194D x) (hxy : x ≤ y) : deductible_194D y := by
  unfold deductible_194D threshold_194D at hx ⊢
  omega

/-- §194DA threshold (life-insurance policy payout), ₹. -/
def threshold_194DA : Nat := 100000

/-- TDS under §194DA applies once the payment exceeds the threshold. -/
abbrev deductible_194DA (paid : Nat) : Prop := threshold_194DA < paid

example : ¬ deductible_194DA 100000 := by decide
example : deductible_194DA 100001 := by decide

/-- §194DA: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194DA_mono (x y : Nat)
    (hx : deductible_194DA x) (hxy : x ≤ y) : deductible_194DA y := by
  unfold deductible_194DA threshold_194DA at hx ⊢
  omega

/-- §194G threshold (lottery ticket commission), ₹. -/
def threshold_194G : Nat := 15000

/-- TDS under §194G applies once the payment exceeds the threshold. -/
abbrev deductible_194G (paid : Nat) : Prop := threshold_194G < paid

example : ¬ deductible_194G 15000 := by decide
example : deductible_194G 15001 := by decide

/-- §194G: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194G_mono (x y : Nat)
    (hx : deductible_194G x) (hxy : x ≤ y) : deductible_194G y := by
  unfold deductible_194G threshold_194G at hx ⊢
  omega

/-- §194H threshold (commission or brokerage), ₹. -/
def threshold_194H : Nat := 15000

/-- TDS under §194H applies once the payment exceeds the threshold. -/
abbrev deductible_194H (paid : Nat) : Prop := threshold_194H < paid

example : ¬ deductible_194H 15000 := by decide
example : deductible_194H 15001 := by decide

/-- §194H: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194H_mono (x y : Nat)
    (hx : deductible_194H x) (hxy : x ≤ y) : deductible_194H y := by
  unfold deductible_194H threshold_194H at hx ⊢
  omega

/-- §194I threshold (rent (annual)), ₹. -/
def threshold_194I : Nat := 240000

/-- TDS under §194I applies once the payment exceeds the threshold. -/
abbrev deductible_194I (paid : Nat) : Prop := threshold_194I < paid

example : ¬ deductible_194I 240000 := by decide
example : deductible_194I 240001 := by decide

/-- §194I: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194I_mono (x y : Nat)
    (hx : deductible_194I x) (hxy : x ≤ y) : deductible_194I y := by
  unfold deductible_194I threshold_194I at hx ⊢
  omega

/-- §194IA threshold (immovable-property transfer), ₹. -/
def threshold_194IA : Nat := 5000000

/-- TDS under §194IA applies once the payment exceeds the threshold. -/
abbrev deductible_194IA (paid : Nat) : Prop := threshold_194IA < paid

example : ¬ deductible_194IA 5000000 := by decide
example : deductible_194IA 5000001 := by decide

/-- §194IA: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194IA_mono (x y : Nat)
    (hx : deductible_194IA x) (hxy : x ≤ y) : deductible_194IA y := by
  unfold deductible_194IA threshold_194IA at hx ⊢
  omega

/-- §194IB threshold (rent paid by individual (monthly)), ₹. -/
def threshold_194IB : Nat := 50000

/-- TDS under §194IB applies once the payment exceeds the threshold. -/
abbrev deductible_194IB (paid : Nat) : Prop := threshold_194IB < paid

example : ¬ deductible_194IB 50000 := by decide
example : deductible_194IB 50001 := by decide

/-- §194IB: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194IB_mono (x y : Nat)
    (hx : deductible_194IB x) (hxy : x ≤ y) : deductible_194IB y := by
  unfold deductible_194IB threshold_194IB at hx ⊢
  omega

/-- §194J threshold (professional or technical fees), ₹. -/
def threshold_194J : Nat := 30000

/-- TDS under §194J applies once the payment exceeds the threshold. -/
abbrev deductible_194J (paid : Nat) : Prop := threshold_194J < paid

example : ¬ deductible_194J 30000 := by decide
example : deductible_194J 30001 := by decide

/-- §194J: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194J_mono (x y : Nat)
    (hx : deductible_194J x) (hxy : x ≤ y) : deductible_194J y := by
  unfold deductible_194J threshold_194J at hx ⊢
  omega

/-- §194K threshold (mutual-fund income), ₹. -/
def threshold_194K : Nat := 5000

/-- TDS under §194K applies once the payment exceeds the threshold. -/
abbrev deductible_194K (paid : Nat) : Prop := threshold_194K < paid

example : ¬ deductible_194K 5000 := by decide
example : deductible_194K 5001 := by decide

/-- §194K: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194K_mono (x y : Nat)
    (hx : deductible_194K x) (hxy : x ≤ y) : deductible_194K y := by
  unfold deductible_194K threshold_194K at hx ⊢
  omega

/-- §194LA threshold (land-acquisition compensation), ₹. -/
def threshold_194LA : Nat := 250000

/-- TDS under §194LA applies once the payment exceeds the threshold. -/
abbrev deductible_194LA (paid : Nat) : Prop := threshold_194LA < paid

example : ¬ deductible_194LA 250000 := by decide
example : deductible_194LA 250001 := by decide

/-- §194LA: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194LA_mono (x y : Nat)
    (hx : deductible_194LA x) (hxy : x ≤ y) : deductible_194LA y := by
  unfold deductible_194LA threshold_194LA at hx ⊢
  omega

/-- §194N threshold (cash withdrawal (annual)), ₹. -/
def threshold_194N : Nat := 10000000

/-- TDS under §194N applies once the payment exceeds the threshold. -/
abbrev deductible_194N (paid : Nat) : Prop := threshold_194N < paid

example : ¬ deductible_194N 10000000 := by decide
example : deductible_194N 10000001 := by decide

/-- §194N: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194N_mono (x y : Nat)
    (hx : deductible_194N x) (hxy : x ≤ y) : deductible_194N y := by
  unfold deductible_194N threshold_194N at hx ⊢
  omega

end Compliance
