/- GENERATED by tools/formalize_tds.py — do not edit by hand.
   TDS deductibility thresholds, FY 2024-25 (simplified pilot:
   thresholds only; rates, PAN status, aggregation windows and
   senior-citizen variants are out of scope). -/

namespace Compliance

/-- §194A threshold (bank and post-office interest), ₹. -/
def threshold_194A : Nat := 40000

/-- TDS under §194A applies once the payment exceeds the threshold. -/
abbrev deductible_194A (paid : Nat) : Prop := threshold_194A < paid

example : ¬ deductible_194A 40000 := by decide
example : deductible_194A 40001 := by decide

/-- §194A: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194A_mono (x y : Nat)
    (hx : deductible_194A x) (hxy : x ≤ y) : deductible_194A y := by
  unfold deductible_194A threshold_194A at hx ⊢
  omega

/-- §194C threshold (contractor payment (single)), ₹. -/
def threshold_194C : Nat := 30000

/-- TDS under §194C applies once the payment exceeds the threshold. -/
abbrev deductible_194C (paid : Nat) : Prop := threshold_194C < paid

example : ¬ deductible_194C 30000 := by decide
example : deductible_194C 30001 := by decide

/-- §194C: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194C_mono (x y : Nat)
    (hx : deductible_194C x) (hxy : x ≤ y) : deductible_194C y := by
  unfold deductible_194C threshold_194C at hx ⊢
  omega

/-- §194I threshold (rent (annual)), ₹. -/
def threshold_194I : Nat := 240000

/-- TDS under §194I applies once the payment exceeds the threshold. -/
abbrev deductible_194I (paid : Nat) : Prop := threshold_194I < paid

example : ¬ deductible_194I 240000 := by decide
example : deductible_194I 240001 := by decide

/-- §194I: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194I_mono (x y : Nat)
    (hx : deductible_194I x) (hxy : x ≤ y) : deductible_194I y := by
  unfold deductible_194I threshold_194I at hx ⊢
  omega

/-- §194J threshold (professional or technical fees), ₹. -/
def threshold_194J : Nat := 30000

/-- TDS under §194J applies once the payment exceeds the threshold. -/
abbrev deductible_194J (paid : Nat) : Prop := threshold_194J < paid

example : ¬ deductible_194J 30000 := by decide
example : deductible_194J 30001 := by decide

/-- §194J: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_194J_mono (x y : Nat)
    (hx : deductible_194J x) (hxy : x ≤ y) : deductible_194J y := by
  unfold deductible_194J threshold_194J at hx ⊢
  omega

end Compliance
