"""Domain formalizer: TDS threshold table → verified Lean 4.

Same pattern as formalize_tax.py: the rule table below is the spec, this
script is a compiler, the Lean kernel checks the output. For each TDS section
it emits

  * the threshold as a named constant,
  * the deductibility predicate (TDS applies once payment exceeds threshold),
  * kernel-checked boundary facts (at the threshold: no TDS; one rupee
    above: TDS) as `example`s,
  * a generated monotonicity theorem per section (if TDS applies at x, it
    applies at every larger payment) — a real theorem with a hypothesis,
    which the statement auditor can meaningfully attack.

Simplified pilot: thresholds only; rates, PAN/no-PAN, aggregation windows
and senior-citizen variants are out of scope and say so.

    python3 tools/formalize_tds.py --out compliance/Compliance/Tds.lean
"""

from __future__ import annotations

import argparse
from pathlib import Path

# section id, human name, annual/single-payment threshold (₹)
SECTIONS = [
    ("194A", "bank and post-office interest", 40_000),
    ("194C", "contractor payment (single)", 30_000),
    ("194I", "rent (annual)", 240_000),
    ("194J", "professional or technical fees", 30_000),
]


def gen() -> str:
    parts = [f"""/- GENERATED by tools/formalize_tds.py — do not edit by hand.
   TDS deductibility thresholds, FY 2024-25 (simplified pilot:
   thresholds only; rates, PAN status, aggregation windows and
   senior-citizen variants are out of scope). -/

namespace Compliance
"""]
    for sec, name, thr in SECTIONS:
        parts.append(f"""
/-- §{sec} threshold ({name}), ₹. -/
def threshold_{sec} : Nat := {thr}

/-- TDS under §{sec} applies once the payment exceeds the threshold. -/
abbrev deductible_{sec} (paid : Nat) : Prop := threshold_{sec} < paid

example : ¬ deductible_{sec} {thr} := by decide
example : deductible_{sec} {thr + 1} := by decide

/-- §{sec}: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_{sec}_mono (x y : Nat)
    (hx : deductible_{sec} x) (hxy : x ≤ y) : deductible_{sec} y := by
  unfold deductible_{sec} threshold_{sec} at hx ⊢
  omega
""")
    parts.append("\nend Compliance\n")
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    src = gen()
    Path(args.out).write_text(src)
    print(f"wrote {args.out} ({len(src.splitlines())} lines, {len(SECTIONS)} sections)")
    return 0


if __name__ == "__main__":
    main()
