"""Domain formalizer: TDS threshold table → verified Lean 4.

Same pattern as formalize_tax.py: the rule table below is the spec, this
script is a compiler, the Lean kernel checks the output. For each TDS section
it emits

  * the threshold as a named constant,
  * the deductibility predicate (TDS applies once payment exceeds threshold),
  * kernel-checked boundary facts (at the threshold: no TDS; one rupee
    above: TDS) as `example`s,
  * a generated monotonicity theorem per section (if TDS applies at x, it
    applies at every larger payment) — a real theorem with a hypothesis,
    which the statement auditor can meaningfully attack.

Simplified pilot: thresholds only (FY 2024-25); rates and PAN/no-PAN rules
are out of scope and say so. Informational only — not tax advice.

    python3 tools/formalize_tds.py --out compliance/Compliance/Tds.lean
"""

from __future__ import annotations

import argparse
from pathlib import Path

# section id, human name, annual/single-payment threshold (₹) — FY 2024-25
SECTIONS = [
    ("192A", "EPF premature withdrawal", 50_000),
    ("193", "interest on securities", 10_000),
    ("194", "dividend", 5_000),
    ("194A", "bank and post-office interest", 40_000),
    ("194A_senior", "bank interest, senior citizen", 50_000),
    ("194B", "lottery and game winnings", 10_000),
    ("194BB", "horse-race winnings", 10_000),
    ("194C", "contractor payment (single)", 30_000),
    ("194C_agg", "contractor payments (annual aggregate)", 100_000),
    ("194D", "insurance commission", 15_000),
    ("194DA", "life-insurance policy payout", 100_000),
    ("194G", "lottery ticket commission", 15_000),
    ("194H", "commission or brokerage", 15_000),
    ("194I", "rent (annual)", 240_000),
    ("194IA", "immovable-property transfer", 5_000_000),
    ("194IB", "rent paid by individual (monthly)", 50_000),
    ("194J", "professional or technical fees", 30_000),
    ("194K", "mutual-fund income", 5_000),
    ("194LA", "land-acquisition compensation", 250_000),
    ("194N", "cash withdrawal (annual)", 10_000_000),
]


def gen() -> str:
    parts = [f"""/- GENERATED by tools/formalize_tds.py — do not edit by hand.
   TDS deductibility thresholds, FY 2024-25 (simplified pilot:
   thresholds only, FY 2024-25; rates and PAN rules are
   out of scope). Informational only — not tax advice. -/

namespace Compliance
"""]
    for sec, name, thr in SECTIONS:
        parts.append(f"""
/-- §{sec} threshold ({name}), ₹. -/
def threshold_{sec} : Nat := {thr}

/-- TDS under §{sec} applies once the payment exceeds the threshold. -/
abbrev deductible_{sec} (paid : Nat) : Prop := threshold_{sec} < paid

example : ¬ deductible_{sec} {thr} := by decide
example : deductible_{sec} {thr + 1} := by decide

/-- §{sec}: if TDS applies at some payment, it applies at every larger one. -/
theorem deductible_{sec}_mono (x y : Nat)
    (hx : deductible_{sec} x) (hxy : x ≤ y) : deductible_{sec} y := by
  unfold deductible_{sec} threshold_{sec} at hx ⊢
  omega
""")
    parts.append("\nend Compliance\n")
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    src = gen()
    Path(args.out).write_text(src)
    print(f"wrote {args.out} ({len(src.splitlines())} lines, {len(SECTIONS)} sections)")
    return 0


if __name__ == "__main__":
    main()
