"""Domain formalizer: Indian income-tax slab table → verified Lean 4.

A deterministic formalization tool for a fixed domain. Input: the slab table
(rates as published). Output: a Lean file with

  * the tax function as a definition (nested slab cases, cumulative constants
    computed here, once, in Python — then PROVED consistent in Lean),
  * kernel-checked regression facts at every slab boundary (as `example`s:
    they are facts, not claims, so the statement auditor skips them),
  * general theorems WITH hypotheses (e.g. §87A rebate ⇒ zero tax below the
    threshold) that the auditor can meaningfully attack.

No LLM anywhere: the rule table is the spec, the generator is a compiler,
and the Lean kernel checks the output. Simplified pilot: new regime,
FY 2024-25; ignores cess, surcharge, marginal relief, and deductions.

    python3 tools/formalize_tax.py --out compliance/Compliance/IncomeTax.lean
"""

from __future__ import annotations

import argparse
from pathlib import Path

# (upper bound in ₹ | None = ∞, marginal rate %)  — new regime, FY 2024-25
SLABS = [
    (300_000, 0),
    (700_000, 5),
    (1_000_000, 10),
    (1_200_000, 15),
    (1_500_000, 20),
    (None, 30),
]
REBATE_87A_LIMIT = 700_000  # taxable income up to which §87A rebate nils the tax


def cumulative() -> list[tuple[int | None, int, int]]:
    """(upper, rate, tax_at_lower_bound) per slab."""
    out, base, lower = [], 0, 0
    for upper, rate in SLABS:
        out.append((upper, rate, base))
        if upper is not None:
            base += (upper - lower) * rate // 100
            lower = upper
    return out


def tax_at(i: int) -> int:
    lower, base = 0, 0
    for upper, rate in SLABS:
        if upper is None or i <= upper:
            return base + (i - lower) * rate // 100
        base += (upper - lower) * rate // 100
        lower = upper
    raise AssertionError


def gen() -> str:
    rows = cumulative()
    branches = []
    lower = 0
    for upper, rate, base in rows:
        expr = f"{base} + (i - {lower}) * {rate} / 100" if rate else "0"
        if upper is None:
            branches.append(f"    {expr}")
        else:
            branches.append(f"    if i ≤ {upper} then {expr}\n    else")
        if upper is not None:
            lower = upper
    body = "\n".join(branches)

    slab_doc = " · ".join(
        f"{'∞' if u is None else f'≤{u:,}'}: {r}%" for u, r in SLABS
    ).replace(",", " ")

    boundary_examples = []
    for upper, _, _ in rows:
        if upper is None:
            continue
        boundary_examples += [
            f"example : slabTax {upper} = {tax_at(upper)} := by decide",
            f"example : slabTax {upper + 1} = {tax_at(upper + 1)} := by decide",
        ]
    spot = [1_600_000, 2_500_000]
    spot_examples = [f"example : slabTax {i} = {tax_at(i)} := by decide" for i in spot]

    return f"""/- GENERATED by tools/formalize_tax.py — do not edit by hand.
   Indian income tax, new regime FY 2024-25 (simplified pilot:
   no cess, surcharge, marginal relief, or deductions).
   Slabs: {slab_doc} -/

namespace Compliance

/-- Income tax (₹) under the new-regime slab table, before §87A rebate. -/
def slabTax (i : Nat) : Nat :=
{body}

/-- Tax payable after the §87A rebate (nil up to ₹{REBATE_87A_LIMIT}). -/
def taxPayable (i : Nat) : Nat :=
  if i ≤ {REBATE_87A_LIMIT} then 0 else slabTax i

-- Kernel-checked regression facts at every slab boundary (and just past it).
-- Stated as `example`s: they are facts, not claims — the auditor skips them.
{chr(10).join(boundary_examples)}
{chr(10).join(spot_examples)}

/-- §87A: taxable income up to the rebate limit ⇒ zero tax payable. -/
theorem rebate_nils_tax (i : Nat) (h : i ≤ {REBATE_87A_LIMIT}) :
    taxPayable i = 0 := by
  simp [taxPayable, h]

/-- Above the rebate limit the slab function is what you pay. -/
theorem above_rebate_pays_slab (i : Nat) (h : {REBATE_87A_LIMIT} < i) :
    taxPayable i = slabTax i := by
  simp [taxPayable, Nat.not_le.mpr h]

end Compliance
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    src = gen()
    Path(args.out).write_text(src)
    print(f"wrote {args.out} ({len(src.splitlines())} lines)")
    print("slab check:", {i: tax_at(i) for i in (300000, 700000, 1000000, 1600000)})
    return 0


if __name__ == "__main__":
    main()
